spring:
  profiles:
    active:
      dev
    group:
      local-env:
        - local
      dev-env:
        - dev
      prod-env:
        - prod
    include:
      - jwt
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB